career_researcher_task:
    description: >
      Conduct a thorough analysis of the individual's career aspirations based on the provided information:
      - Current position: {current_job_title}, {current_salary}, {current_job_market}
      - Desired position: {desired_job_title}, {desired_salary}, {desired_job_market}
      - Professional context: {current_industry} to {desired_industry}
      - Role evolution: {current_job_function} to {desired_job_function}
      - Skills assessment: {current_skill_set} vs {desired_skill_set}
      - Experience level: {current_level_of_experience} to {desired_level_of_experience}
      - Location factors: {current_location} to {desired_location}
      - Educational background: {current_level_of_education} to {desired_level_of_education}
      Provide expert guidance and identify a suitable advised career path.
    expected_output: >
      A structured career analysis report including:
      - Summary of the current career situation.
      - Feasibility analysis of transitioning to the desired position.
      - Identified gaps in skills, education, and experience.
      - Suggested career options based on strengths and market trends.
      - Recommended upskilling and certification programs.
      - Suggested industries and job roles for smooth transition.
      - Final advised career path with justification.
      The output should be a single string containing the advised career path.
    agent: career_researcher

roadmap_generator_task:
    description: >
      Generate a detailed and personalized roadmap for pursuing a career transition.
      This roadmap should be based on the following information:
      - Current position: {current_job_title}, {current_salary}, {current_job_market}
      - Desired position: {desired_job_title}, {desired_salary}, {desired_job_market}
      - Professional context: {current_industry} to {desired_industry}
      - Role evolution: {current_job_function} to {desired_job_function}
      - Skills assessment: {current_skill_set} vs {desired_skill_set}
      - Experience level: {current_level_of_experience} to {desired_level_of_experience}
      - Location factors: {current_location} to {desired_location}
      - Educational background: {current_level_of_education} to {desired_level_of_education}
      The roadmap should include actionable steps, timelines, and relevant resources.
      Use the advised career path provided by the career researcher: {advised_career}
    expected_output: >
      A structured career roadmap including:
      - Step-by-step transition plan from current position to the advised career path.
      - Timeline with short-term and long-term milestones.
      - Required skills and certifications with learning resources.
      - Suggested networking and mentorship opportunities.
      - Recommended projects, internships, or freelancing options.
      - Relocation and financial planning considerations if applicable.
    agent: roadmap_generator

react_flow_roadmap_generator_task:
    description: >
      Convert the text-based career roadmap generated by the 'roadmap_generator' into a
      ReactFlowJsonObject. This JSON object should visually represent the career roadmap
      as a flow diagram with nodes and edges, suitable for rendering with a React Flow library.
      The roadmap should be based on the transition to the advised career path: {advised_career}
      Ensure the output is a valid JSON format.
    expected_output: >
      A valid JSON representation of the career roadmap, structured as:
      - Nodes: Key steps in the roadmap (e.g., "Learn Python", "Get Certified", "Apply for Jobs").
      - Edges: Connections between steps, representing the flow of progress.
      - Additional metadata: Labels, descriptions, and tooltips for each node.
      - A hierarchical structure to depict the roadmap visually.
    agent: react_flow_roadmap_generator

